language: php

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - if php -i | grep -q xdebug; then phpenv config-rm xdebug.ini; fi;
  - if [ "$GITHUB_COMPOSER_AUTH" ]; then composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH; fi;

before_script:
  - |
    set -e
    if [[ "$TYPO3_VERSION" == "^6.2" ]]; then
      composer require typo3/cms-composer-installers="1.2.5 as 1.1.4" --no-update;
      composer require typo3/cms "$TYPO3_VERSION";
    else
      composer require nimut/typo3-complete "$TYPO3_VERSION";
    fi
    git checkout composer.json;
    export TYPO3_PATH_WEB=$PWD/.Build/public;

script:
  - |
    set -e
    if [ "$TRAVIS_ALLOW_FAILURE" == "true" ]; then echo "skip testing"; return; fi;
    echo "Running unit tests";
    composer test:phpunit;

    echo "Running php lint";
    composer test:phplint

jobs:
  fast_finish: true
  include:
    - stage: test
      php: 7.2
      env: TYPO3_VERSION=^9.5
    - stage: test
      php: 7.2
      env: TYPO3_VERSION=^8.7
    - stage: test
      php: 7.1
      env: TYPO3_VERSION=^8.7
    - stage: test
      php: 7.0
      env: TYPO3_VERSION=^8.7
    - stage: test
      php: 7.1
      env: TYPO3_VERSION=^7.6
    - stage: test
      php: 7.0
      env: TYPO3_VERSION=^7.6
    - stage: test
      php: 5.6
      env: TYPO3_VERSION=^7.6
    - stage: test
      dist: trusty
      php: 5.5
      env: TYPO3_VERSION=^7.6
    - stage: test
      php: 5.6
      env: TYPO3_VERSION=^6.2
    - stage: test
      dist: trusty
      php: 5.5
      env: TYPO3_VERSION=^6.2
    - stage: test
      dist: trusty
      php: 5.4
      env: TYPO3_VERSION=^6.2
    - stage: test
      dist: precise
      php: 5.3
      env: TYPO3_VERSION=^6.2
    - stage: deploy to ter
      if: tag IS present AND env(TYPO3_ORG_USERNAME) IS present AND env(TYPO3_ORG_PASSWORD) IS present
      php: 7.1
      env: TYPO3_VERSION=
      install: skip
      before_script: skip
      script:
        - >
          echo "Preparing upload of release ${TRAVIS_TAG} to TER";
          composer global require helhum/ter-client;

        - >
          TAG_MESSAGE=`git tag -n10 -l $TRAVIS_TAG | sed 's/^[0-9.]*[ ]*//g'`;
          echo "Uploading release ${TRAVIS_TAG} to TER";
          $HOME/.composer/vendor/bin/ter-client upload caretaker_instance . -u "$TYPO3_ORG_USERNAME" -p "$TYPO3_ORG_PASSWORD" -m "$TAG_MESSAGE";
